{{- if .Values.hooks.presync.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "kaz-generic-chart.fullname" . }}-presync-hook
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
    {{- with .Values.hooks.presync.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  template:
    metadata:
      labels:
        {{- include "kaz-generic-chart.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: presync-hook
    spec:
      restartPolicy: Never
      containers:
      - name: presync-hook-container
        image: quay.io/skopeo/stable:latest
        command:
          - sh
          - -c
          - echo "Hello world !!!"
  backoffLimit: 3
{{- end }}
